"""Texto editorial original. Fontes públicas consultadas em setembro de 2026."""
SOURCES={
'E1':('Embrapa. Horta em casa.','https://www.infoteca.cnptia.embrapa.br/infoteca/bitstream/doc/1000838/1/Horta-em-casa.pdf'),
'E2':('Embrapa. Horta em pequenos espaços.','https://www.infoteca.cnptia.embrapa.br/handle/doc/927690'),
'E3':('Embrapa Hortaliças. Compostagem.','https://www.embrapa.br/en/web/hortalicas/hortalica-nao-e-so-salada/secoes/compostagem'),
'U1':('University of Maryland Extension. Growing vegetables in containers and salad tables.','https://www.extension.umd.edu/resource/growing-vegetables-containers-and-salad-tables'),
'U2':('University of Maryland Extension. Maintaining container grown vegetables.','https://www.extension.umd.edu/resource/maintaining-container-grown-vegetables'),
'U3':('University of Maryland Extension. Starting vegetable seeds indoors.','https://www.extension.umd.edu/resource/starting-vegetable-seeds-indoors'),
'U4':('University of Maryland Extension. Fertilizing vegetable gardens.','https://www.extension.umd.edu/resource/fertilizing-vegetable-gardens'),
'U5':('University of Maryland Extension. How to make compost at home.','https://www.extension.umd.edu/resource/how-make-compost-home'),
'U6':('University of Maryland Extension. Aphids in home gardens.','https://www.extension.umd.edu/resource/aphids-home-gardens'),
'U7':('University of Maryland Extension. Vegetable succession and companion planting.','https://www.extension.umd.edu/resource/vegetable-succession-and-companion-planting'),
'U8':('University of Maryland Extension. Growing basil in a home garden.','https://www.extension.umd.edu/resource/growing-basil-home-garden'),
'U9':('University of Maryland Extension. When to plant vegetables.','https://www.extension.umd.edu/resource/when-plant-vegetables'),
'M1':('University of Minnesota Extension. Growing herbs in home gardens.','https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/growing-herbs'),
'M2':('University of Minnesota Extension. Growing tomatoes in home gardens.','https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/growing-tomatoes'),
'M3':('University of Minnesota Extension. Planting the vegetable garden.','https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/planting-the-vegetable-garden'),
'M4':('University of Minnesota Extension. Companion planting in home gardens.','https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/companion-planting-in-home-gardens'),
'M5':('University of Minnesota Extension. Small-scale hydroponics.','https://extension.umn.edu/garden-and-home/yard-and-garden/gardening-in-minnesota/small-scale-hydroponics'),
'M6':('University of Minnesota Extension. Container gardening for small spaces.','https://extension.umn.edu/news/container-gardening-small-spaces-big-beauty-tiny-places'),
'O1':('Oregon State University Extension. Coffee grounds boost soil health.','https://extension.oregonstate.edu/news/coffee-grounds-boost-soil-health-help-control-slugs'),
'I1':('University of Illinois Extension. How to harvest and store garden vegetables.','https://extension.illinois.edu/sites/default/files/how_to_harvest_and_store_garden_vegetables.pdf'),
'F1':('FDA. Selecting and serving produce safely.','https://www.fda.gov/food/buy-store-serve-safe-food/selecting-and-serving-produce-safely'),
}

def P(title,kicker,paras=(),steps=(),tip='',refs=(),image=None,table=None,fields=(),diagram=None):
 return dict(title=title,kicker=kicker,paras=list(paras),steps=list(steps),tip=tip,refs=list(refs),image=image,table=table,fields=list(fields),diagram=diagram)

BOOKS=[]
BOOKS.append(dict(slug='01-horta-infinita-essencial',title='Guia Essencial',subtitle='Do primeiro vaso aos cuidados que fazem diferença.',tag='MÓDULOS 1 A 5',cover='manjericao-vaso.webp',pages=[
P('Antes de plantar, observe.','COMO USAR ESTE GUIA',[
'Comece com uma muda e um recipiente. Sua primeira meta é aprender a reconhecer a luz, a umidade e o crescimento de uma planta; aumentar a horta vem depois. Leia na ordem dos módulos ou use o sumário para consultar uma dúvida específica.',
'Este é um guia de cultivo doméstico. As decisões variam com espécie, cultivar, estação e região. Informações da embalagem de sementes e recomendações locais têm prioridade sobre médias gerais. Não há prazo garantido de colheita.',
'As fotos de ambientação são ilustrativas, não registros de resultados de alunos. O texto foi preparado a partir das fontes indicadas ao final; as instituições citadas não endossam este produto.'],steps=['Módulo 1: escolha o espaço.','Módulo 2: prepare o recipiente.','Módulo 3: plante.','Módulo 4: acompanhe os cuidados.','Módulo 5: escolha espécies e colha.'],tip='Leia com um caderno ao lado. Anote o que acontece no seu vaso, não apenas o que você espera que aconteça.'),
P('Encontre a luz do seu espaço.','MÓDULO 1 · PRIMEIROS PASSOS',[
'Uma janela clara não é necessariamente um local com sol direto. Observe se os raios atingem as folhas e por quanto tempo. Folhosas toleram menos sol que muitas plantas cultivadas pelos frutos, mas nenhuma horta produtiva vive em um canto escuro.',
'Como referência inicial, procure cerca de 6 horas de sol direto para cultivos exigentes, como tomate. Em locais com 4 a 6 horas, experimente folhosas e temperos compatíveis. Calor intenso e luz refletida podem exigir adaptação. Essas faixas orientam a escolha, não garantem produção.'],steps=['Observe o espaço de manhã, perto do meio-dia e à tarde.','Anote o início e o fim dos períodos de sol direto.','Repita em dias diferentes e reavalie quando a estação mudar.'],tip='Comece com a planta que combina com a luz disponível. Não compre todas as espécies antes de conhecer o espaço.',refs=['U1','E2'],diagram='light'),
P('Seu primeiro projeto em uma página.','MÓDULO 1 · PLANEJAMENTO',[
'Preencha antes de comprar. Um projeto pequeno ajuda a separar as necessidades da planta dos objetos que apenas enfeitam o ambiente. Para o início, bastam recipiente compatível, substrato, muda ou sementes, água e uma forma de observar a rotina.',
'Vasos molhados são pesados. Apoie-os em superfícies estáveis; não pendure recipientes sobre áreas de passagem sem estrutura apropriada. Confirme regras do condomínio e a segurança de suportes de varanda.'],fields=['Minha espécie e cultivar:','Local e horas aproximadas de sol direto:','Recipiente: medidas, volume e furos:','Quem cuida quando eu estiver fora:','O que já tenho / o que preciso comprar:'],tip='Critério de sucesso da primeira semana: manter o plantio identificado e registrar as observações. Não é colher em sete dias.'),
P('Escolha um vaso que funcione.','MÓDULO 2 · RECIPIENTES',[
'O recipiente precisa permitir saída de água e ter espaço para as raízes. Prefira vasos próprios para cultivo ou embalagens resistentes que tenham sido usadas com alimentos. Não reutilize recipientes de tinta, combustível ou produtos químicos.',
'Leia a recomendação da cultivar. Um tomateiro compacto e um de crescimento indeterminado têm exigências diferentes; o fruto pequeno não significa planta pequena. Recipientes maiores costumam sofrer menos oscilações rápidas de umidade.'],steps=['Confira os furos antes de colocar substrato.','Mantenha a saída de água livre, sem vedar a base contra o piso.','Use cachepô apenas como revestimento e retire a água acumulada.','Não coloque uma camada de pedras como solução para drenagem: ela reduz o espaço das raízes e pode piorar o escoamento.'],tip='Drenagem resulta do conjunto: furos livres, substrato poroso e rega adequada.',refs=['U1','M6']),
P('Substrato: ar e água em equilíbrio.','MÓDULO 2 · SOLO E SUBSTRATO',[
'Em vasos, use substrato próprio para hortaliças ou cultivo em recipientes, de procedência conhecida. Terra retirada do quintal pode compactar, carregar sementes indesejadas e não drenar bem no espaço restrito.',
'Leia a embalagem: o material pode vir adubado ou exigir nutrição complementar. Não some adubos automaticamente. Misturas caseiras variam com os ingredientes; não existe uma proporção universal de terra, areia e composto que funcione para todos os vasos.'],steps=['Umedeça o substrato se estiver muito seco, sem transformá-lo em lama.','Preencha o vaso sem prensar com força.','Deixe espaço abaixo da borda para a rega.','Após molhar, verifique se o excesso sai e se o nível assentou.'],tip='Solo encharcado por muito tempo pode indicar mistura inadequada, furos bloqueados ou excesso de rega. Investigue antes de adubar.',refs=['U1','U2'],diagram='drain'),
P('Semente ou muda?','MÓDULO 3 · PLANTIO',[
'Sementes permitem acompanhar o ciclo inteiro e escolher variedades. Mudas encurtam a etapa inicial e podem facilitar o primeiro contato com o cultivo. Em ambos os casos, compre material identificado e adequado à época da sua região.',
'Na escolha da muda, procure crescimento firme e folhas sem infestação evidente. Observe o verso das folhas e a base do caule. Evite plantas muito esticadas, tombadas ou com raízes formando uma massa apertada fora do recipiente.'],table=[['Sementes','Mudas'],['Exigem acompanhar a germinação e o desbaste.','Exigem adaptação e transplante cuidadoso.'],['Rabanete e coentro são opções para semeadura no local definitivo.','Manjericão e alface podem ser iniciados com mudas.'],['Confira validade, cultivar e profundidade no envelope.','Confira espécie, origem e condições em que foram produzidas.']],tip='Nome popular não substitui identificação. Guarde a embalagem ou etiqueta.',refs=['M3','U3']),
P('Semeie sem perder a identificação.','MÓDULO 3 · PASSO A PASSO',[
'A profundidade depende da espécie. Sementes muito pequenas ficam próximas da superfície; outras precisam de cobertura maior. Siga o envelope. Enterrar demais pode dificultar a emergência, e regar com jato forte pode deslocar as sementes.'],steps=['Prepare o substrato e distribua as sementes com espaço.','Cubra na profundidade indicada; pressione levemente para contato.','Regue com fluxo delicado e mantenha umidade sem encharcar.','Identifique espécie, cultivar e data.','Quando surgirem folhas verdadeiras, faça o desbaste se houver excesso de plantas, respeitando o espaçamento recomendado.'],tip='Ausência de brotos em poucos dias não significa falha. Compare com a faixa de germinação do lote e considere a temperatura.',refs=['U3'],fields=['Espécie / cultivar / data da semeadura:','Profundidade e germinação previstas no envelope:','Data em que observei a emergência:']),
P('Transplante sem apressar a muda.','MÓDULO 3 · MUDANÇA DE RECIPIENTE',[
'Uma muda acostumada a ambiente protegido pode sofrer ao ir direto para sol forte e vento. Faça a adaptação gradualmente, observando sua resposta. O calendário fixo é menos útil que acompanhar a planta e o clima.',
'Na maioria das hortaliças, mantenha a altura em que a muda já estava plantada. Existem exceções, como técnicas específicas para tomate; não enterre o colo de qualquer espécie por imitação.'],steps=['Umedeça o torrão e prepare uma cova compatível.','Retire a muda segurando o torrão, sem puxar o caule.','Acomode, complete as laterais e firme suavemente.','Regue para acomodar o substrato e acompanhe a drenagem.','Proteja de extremos durante a adaptação e observe as folhas novas.'],tip='Folhas verdadeiras são as que surgem após as primeiras folhas da germinação. Use o desenvolvimento da muda para avaliar o transplante.',refs=['M3']),
P('A rega começa pela observação.','MÓDULO 4 · ÁGUA',[
'Confira o substrato antes de regar: toque a camada superficial e um pouco abaixo dela. Considere também o peso do vaso e a espécie. Um mesmo recipiente pode secar rapidamente em um dia quente e continuar úmido no seguinte.',
'Quando houver necessidade, molhe o substrato de forma uniforme até observar escoamento. Aguarde drenar e descarte a água parada. Não deixe o vaso secar repetidamente até a planta murchar nem mantenha raízes permanentemente encharcadas.'],steps=['Substrato ainda úmido? Reavalie mais tarde.','Substrato secando e vaso leve? Verifique a necessidade de água.','Planta murcha com substrato molhado? Investigue drenagem e raízes; não regue por reflexo.'],tip='Checar diariamente não significa regar diariamente. Não existe um número de copos válido para todas as plantas.',refs=['U2'],diagram='water'),
P('Uma rotina simples de cuidado.','MÓDULO 4 · ACOMPANHAMENTO',[
'Escolha um momento para observar sua horta. A regularidade da inspeção importa mais que fazer muitas intervenções de uma vez. O registro ajuda a perceber alterações após mudanças de clima, posição ou manejo.',
'No calor, vasos podem pedir checagens mais frequentes. Em dias frios ou chuvosos, o consumo de água pode diminuir. Ajuste sua observação sem transformar a horta em um cronograma automático de rega e adubo.'],table=[['Quando observar','O que conferir'],['A cada dia','Umidade, firmeza das folhas, escoamento e alterações visíveis.'],['Ao longo da semana','Verso das folhas, brotações, estabilidade do suporte e identificação.'],['Após vento, chuva ou calor forte','Tombamento, excesso de água, dano em folhas e mudança na secagem.']],tip='Se mudar o local, anote a data. Isso facilita relacionar o novo ambiente à resposta da planta.',fields=['Minha observação de hoje:','Uma mudança que fiz e por quê:']),
P('Manjericão e cebolinha.','MÓDULO 5 · TEMPEROS',[
'Manjericão combina com locais ensolarados e clima mais quente. Faça pequenas colheitas de ramos, cortando acima de um par de folhas e preservando área foliar. Retirar hastes florais ajuda a manter o foco na produção de folhas. Evite colher a planta inteira de uma vez.',
'Cebolinha pode ser iniciada por sementes ou divisão de uma touceira saudável. Deixe espaço para o conjunto crescer e preserve a base na colheita. O nome popular pode designar espécies diferentes; observe a identificação da muda.',
'Separe o cultivo em recipientes próprios no início. Assim fica mais fácil ajustar água e observar cada planta sem confundir suas respostas.'],image='manjericao-vaso.webp',tip='Comece por um tempero que você já usa na cozinha. Isso torna mais fácil acompanhar o momento de colher.',refs=['U8','M1']),
P('Alface, rúcula e rabanete.','MÓDULO 5 · HORTALIÇAS',[
'Folhosas são uma alternativa para acompanhar crescimento e fazer pequenas colheitas. A tolerância ao calor varia entre cultivares; prefira as indicadas para sua estação. Calor excessivo pode acelerar o florescimento e alterar a qualidade das folhas.',
'Rabanete é semeado, em geral, no recipiente definitivo. Faça desbaste para que as raízes tenham espaço. Acompanhe o ponto indicado na embalagem e não use o tamanho das folhas como único sinal de maturidade.'],steps=['Não semeie tudo junto em uma jardineira pequena.','Observe o espaçamento da cultivar e deixe circulação de ar.','Em alfaces de folhas, colha folhas externas sem destruir o centro de crescimento, quando a variedade permitir.','Registre a resposta local antes de repetir a mesma escolha em outra estação.'],tip='Ciclo informado pelo fornecedor é estimativa, não promessa. Semeadura e transplante podem ter contagens diferentes.',refs=['U9','E1']),
P('Tomate exige um pouco mais.','MÓDULO 5 · PRIMEIROS FRUTOS',[
'Antes de escolher tomate-cereja, confira o porte da cultivar: existem plantas compactas e outras que crescem bastante. Reserve recipiente compatível, boa luz e suporte instalado cedo. Acompanhe rega e nutrição com atenção maior que a de um pequeno vaso de temperos.',
'Amarre sem apertar o caule e reavalie os pontos de apoio durante o crescimento. Não retire todos os brotos laterais por regra; a condução depende do hábito de crescimento e do sistema escolhido.'],image='tomates-cereja.webp',tip='Para o primeiro cultivo, escolha uma cultivar indicada para vaso e siga as informações do produtor de sementes.',refs=['M2']),
P('Colha e leve para a cozinha.','MÓDULO 5 · COLHEITA',[
'Use mãos e utensílios limpos. Colha partes saudáveis e na quantidade que pretende usar; evite puxar a planta ou esmagar os ramos. Separe folhas deterioradas e não misture material doente à colheita.',
'Antes de consumir, lave os vegetais em água corrente potável. Não utilize detergente ou sabão nos alimentos. Cultivar em casa não elimina a necessidade de higiene. Mantenha alimentos afastados de superfícies e utensílios que tiveram contato com carnes cruas.',
'O armazenamento depende da espécie. Folhas delicadas e frutos não pedem exatamente as mesmas condições. Planeje a colheita próxima do uso para reduzir perdas e consulte orientação específica se precisar conservar por mais tempo.'],tip='Não consuma uma planta cuja identificação seja duvidosa. Este guia não ensina reconhecimento de plantas silvestres comestíveis.',refs=['F1','I1']),
P('Primeiros 7 dias: observar e aprender.','SEU PLANO DE AÇÃO',[
'Este roteiro organiza tarefas, não promete germinação nem colheita em uma semana. Se uma etapa exigir mais tempo, repita antes de avançar. Você pode preencher o registro no celular ou imprimir esta página.'],table=[['Etapa','Ação prática'],['1','Mapeie a luz e escolha uma espécie.'],['2','Separe o recipiente e confira os furos.'],['3','Prepare o substrato e identifique o plantio.'],['4','Observe umidade e resposta das folhas.'],['5','Confira drenagem e estabilidade do vaso.'],['6','Fotografe do mesmo ângulo para comparar.'],['7','Anote o que funcionou e a próxima dúvida.']],fields=['O que aprendi sobre meu espaço:','O que farei diferente na próxima semana:'],tip='Sua primeira conquista é construir uma rotina que você consegue manter.')
]))

BOOKS.append(dict(slug='02-horta-infinita-plus',title='Guia Plus',subtitle='Adubação, observação e manejo de problemas comuns.',tag='MÓDULOS 6 E 7',cover='cebolinha-alecrim.webp',pages=[
P('Cuide antes de corrigir.','COMO USAR ESTE GUIA',[
'Use este volume depois dos fundamentos do Essencial. Aqui o foco é observar a planta, entender a nutrição e agir diante de problemas comuns sem misturar várias intervenções.',
'Fotografias ajudam a comparar o crescimento, mas não substituem identificação de pragas ou diagnóstico de doenças. Quando a causa não estiver clara, procure orientação de assistência técnica rural ou de um profissional habilitado na sua região.'],steps=['Módulo 6: adubação, rótulos e compostagem.','Módulo 7: inspeção, prevenção e decisão de manejo.','Registros: transforme observações em histórico do vaso.'],tip='Este guia prioriza prevenção e manejo físico. Não apresenta receitas de agrotóxicos nem misturas domésticas para pulverizar alimentos.'),
P('Nutrição não corrige tudo.','MÓDULO 6 · ADUBAÇÃO',[
'Plantas precisam de nutrientes, mas folhas amarelas também podem aparecer por problemas de água, raízes, luz ou envelhecimento. Antes de adicionar adubo, revise as condições do vaso e o histórico de aplicação.',
'Substratos comerciais podem conter fertilizantes. Em canteiros, análise de solo orienta a correção; em vasos, leve em conta o produto utilizado, a espécie e o volume do recipiente. Adubar sem necessidade pode elevar a concentração de sais e prejudicar raízes.'],steps=['Confira se o substrato já veio adubado.','Leia a dose e a frequência no produto indicado para a cultura.','Registre aplicação, quantidade e resposta.','Não misture várias fontes para tentar acelerar o crescimento.'],tip='Natural não significa isento de dose. Composto, húmus e outros materiais também alteram as condições do cultivo.',refs=['U4']),
P('Leia o rótulo antes da colher.','MÓDULO 6 · APLICAÇÃO RESPONSÁVEL',[
'Use um medidor exclusivo e guarde o produto identificado. Não transforme uma recomendação em gramas por área em uma dose por vaso sem conversão adequada. Produtos de liberação lenta e solúveis seguem instruções diferentes.',
'Se a embalagem indicar 2 g por litro de água, preparar 500 mL exigiria 1 g. Este é apenas um exemplo de cálculo, não uma recomendação de adubação. A concentração correta é a do produto, da cultura e da fase de crescimento.'],table=[['Informação','O que anotar'],['Produto e composição','Nome, lote e tipo de aplicação.'],['Recomendação da embalagem','Dose, intervalo e cultura indicada.'],['Recipiente ou área','Volume do vaso ou dimensões do canteiro.'],['Minha aplicação','Data, quantidade e condições da planta.']],tip='Não use utensílios de cozinha com fertilizantes. Armazene longe de alimentos, crianças e animais.',refs=['U4','U2']),
P('Compostagem: um processo, não um truque.','MÓDULO 6 · MATÉRIA ORGÂNICA',[
'Compostagem transforma resíduos orgânicos por atividade biológica. Em uma operação doméstica simples, mantenha mistura de resíduos vegetais úmidos e materiais secos, com oxigênio e umidade suficiente para a decomposição.',
'Comece com restos crus de frutas e hortaliças, folhas secas e material vegetal limpo. Evite carnes, gordura, laticínios, fezes de animais e plantas doentes na composteira doméstica de iniciante. Sistemas especializados podem aceitar outros resíduos, mas exigem manejo próprio.'],steps=['Pique resíduos grandes para facilitar o manejo.','Misture porções úmidas com material seco.','Cubra novas adições e evite deixar alimento exposto.','Se houver encharcamento e mau cheiro, acrescente secos e favoreça aeração.'],tip='Não use odor como única medida de maturidade. O composto pronto deve estar estabilizado, com aspecto escuro e cheiro de terra.',refs=['E3','U5']),
P('O que não colocar direto no vaso.','MÓDULO 6 · RECEITAS POPULARES',[
'Borra de café não é um fertilizante completo e imediato. Em excesso, pode formar uma camada compacta e afetar o cultivo. Para iniciantes, a compostagem controlada é uma rota mais previsível que despejar resíduos repetidamente ao redor da planta.',
'Cascas de banana e outros restos frescos precisam se decompor. Colocá-los no vaso não permite conhecer a dose de nutrientes que chegará às raízes e pode atrair insetos. Evite líquidos fermentados sem controle e água acumulada de composteiras em folhas comestíveis.'],steps=['Prefira compostos estabilizados de origem conhecida.','Não trate plantas murchas com uma mistura de resíduos.','Não prometa corrigir falta de cálcio com casca de ovo aplicada na hora.','Se houver dúvida sobre a composição, escolha orientação técnica e produto identificado.'],tip='O objetivo é aproveitar resíduos com método, não substituir qualquer necessidade da planta por uma receita caseira.',refs=['O1','U5']),
P('Inspecione de cima a baixo.','MÓDULO 7 · PREVENÇÃO',[
'Reserve alguns minutos para olhar brotos, verso das folhas, caule e superfície do substrato. Observe se o dano está aumentando e se aparece em uma única planta ou em várias. Não mate todo inseto: há visitantes inofensivos e inimigos naturais de pragas.',
'Ao trazer uma muda nova, mantenha-a separada enquanto observa sua condição. Remova folhas caídas e evite excesso de plantas no mesmo espaço. Um ambiente arejado e uma rotina de inspeção tornam os problemas mais fáceis de perceber.'],steps=['Fotografe a planta inteira e depois o detalhe.','Anote quando o sintoma começou.','Procure insetos, ovos, fezes e teias sem assumir a causa.','Identifique antes de escolher qualquer produto.'],tip='Mudança de cor isolada não confirma uma praga. Compare a planta com seu próprio histórico.',refs=['U6'],fields=['Local do dano e quando apareceu:','O que consigo ver com clareza:']),
P('Sinais ajudam; não fecham diagnóstico.','MÓDULO 7 · LEITURA DA PLANTA',[
'Use o quadro como roteiro de investigação. Várias causas produzem sinais semelhantes; nenhuma linha substitui diagnóstico. Evite adubar, podar e pulverizar no mesmo dia sem saber o que está acontecendo.'],table=[['O que observo','O que vale conferir primeiro'],['Murcha com substrato seco','Umidade abaixo da superfície e uniformidade da rega.'],['Murcha com substrato molhado','Escoamento, raízes e tempo de encharcamento.'],['Folhas amareladas','Idade das folhas, luz, água e histórico de adubação.'],['Furos ou bordas comidas','Verso das folhas, presença de animais e progressão do dano.'],['Crescimento esticado','Luz disponível e competição entre plantas.']],tip='Se a planta piora rapidamente ou o problema se espalha, isole o recipiente quando possível e procure orientação local.',refs=['U2','U3']),
P('Pulgões: comece pelo manejo físico.','MÓDULO 7 · UM EXEMPLO PRÁTICO',[
'Pulgões são insetos pequenos que podem se reunir em brotos e no verso de folhas. Podem produzir uma secreção pegajosa e causar deformações. A aparência varia; confirme o que está observando antes de agir.',
'Em uma infestação pequena e localizada, a remoção manual cuidadosa ou um jato de água compatível com a resistência da planta pode ajudar. Evite danificar mudas frágeis e reavalie depois. Preserve inimigos naturais.'],steps=['Observe a extensão do problema.','Separe o vaso se isso facilitar o acompanhamento.','Remova cuidadosamente os insetos visíveis.','Reinspecione as brotações nos dias seguintes.'],tip='Se for necessário usar um produto, verifique indicação para a cultura comestível, registro e instruções locais. Não substitua por detergente doméstico.',refs=['U6']),
P('Recupere com uma mudança por vez.','MÓDULO 7 · TOMADA DE DECISÃO',[
'Uma folha danificada pode não voltar ao aspecto anterior. O crescimento novo e a estabilidade da planta são sinais mais úteis para acompanhar a resposta. Não descarte uma planta só porque uma folha antiga continua amarela.',
'Defina o problema observado, uma hipótese e uma ação proporcional. Reavalie em um intervalo compatível com o caso. Problemas agudos pedem ajuda mais rápida; crescimento e nutrição não mudam de um dia para o outro.'],table=[['Registro','Exemplo de raciocínio, não diagnóstico'],['Observação','O substrato continua muito úmido.'],['Verificação','O cachepô está com água na base.'],['Ação','Retirar a água e liberar o escoamento.'],['Acompanhamento','Observar umidade e crescimento novo.']],fields=['Minha observação / hipótese:','Ação escolhida e data:','O que aconteceu depois:']),
P('Meu calendário de cuidados.','FOLHA PARA IMPRIMIR',[
'Preencha uma linha por inspeção. Marque a ação apenas quando ela for necessária. Registros diferentes para plantas diferentes ajudam a evitar que toda a horta receba o mesmo tratamento.'],table=[['Data / vaso','Luz e umidade','Ação / resposta'],['________________','________________','________________'],['________________','________________','________________'],['________________','________________','________________'],['________________','________________','________________'],['________________','________________','________________'],['________________','________________','________________']],fields=['Produto aplicado, dose do rótulo e quantidade usada:','Próxima verificação:'],tip='Este registro organiza a rotina. A frequência de adubação e rega vem da necessidade do cultivo, não das linhas da tabela.')
]))

BOOKS.append(dict(slug='03-horta-infinita-avancado',title='Guia Avançado',subtitle='Mais organização para aproveitar espaço e continuar plantando.',tag='MÓDULOS 8 E 9',cover='horta-vertical.webp',pages=[
P('Avance com uma base estável.','COMO USAR ESTE GUIA',[
'Avançar não significa comprar uma estrutura grande. Significa entender o que já funciona, organizar a ocupação do espaço e experimentar uma mudança que você consiga acompanhar.',
'O módulo 8 trata de horta vertical, associação de cultivos, sucessão e mudas. O módulo 9 apresenta princípios do cultivo sem solo e planejamento. A parte de hidroponia é introdutória: não é projeto executivo nem formulação de solução nutritiva.'],steps=['Antes de ampliar, reveja luz, água e identificação dos vasos.','Expanda uma parte do cultivo por vez.','Registre despesas, trabalho e colheitas para avaliar sua experiência.'],tip='Uma horta pequena bem acompanhada é uma base melhor que muitos vasos sem rotina.'),
P('Aproveite a altura com planejamento.','MÓDULO 8 · HORTA VERTICAL',[
'Uma estrutura vertical redistribui os vasos, mas não cria luz. Prateleiras superiores podem sombrear as inferiores. Observe o espaço com a estrutura montada e ajuste a posição das plantas conforme suas necessidades.',
'Considere o peso do conjunto molhado, o acesso para regar e o destino da água. Paredes precisam de fixação adequada e proteção contra umidade. Use estrutura dimensionada para o local; este guia não especifica cargas ou fixadores.'],steps=['Meça altura, largura e acesso com os braços.','Confirme estabilidade antes de colocar os vasos.','Posicione os recipientes sem bloquear a saída de água.','Confira se folhas das plantas maiores sombreiam as demais.'],image='horta-vertical.webp',tip='Faça primeiro um teste com poucos vasos, em posição fácil de alcançar.',refs=['M6']),
P('Plantas próximas precisam de espaço.','MÓDULO 8 · CONSÓRCIO',[
'Cultivar espécies próximas pode aproveitar melhor a área e diversificar a horta. Isso exige compatibilidade de luz, água, espaço e duração do ciclo. Uma associação não elimina o espaçamento mínimo nem a necessidade de manejo.',
'Há muitas listas populares de plantas que supostamente afastam pragas. Nem todas têm apoio em pesquisa. Não trate manjericão ao lado de tomate, por exemplo, como garantia de proteção. Observe o conjunto e mantenha a inspeção.'],table=[['Critério','Pergunta antes de combinar'],['Altura','Uma planta vai sombrear a outra?'],['Raízes','O recipiente comporta as duas adultas?'],['Água','As necessidades são compatíveis?'],['Colheita','Consigo acessar sem danificar a vizinha?'],['Sanidade','O conjunto dificulta observar folhas e caules?']],tip='Vasos separados, colocados lado a lado, permitem testar combinações sem compartilhar o mesmo volume de substrato.',refs=['M4']),
P('Plante em pequenos lotes.','MÓDULO 8 · SUCESSÃO',[
'Sucessão de plantio é organizar entradas e saídas da horta. Em vez de semear tudo no mesmo dia, você pode distribuir pequenos lotes, desde que a estação continue adequada. A reposição não precisa esperar todos os vasos ficarem vazios.',
'Como exemplo de organização, escolha três recipientes para uma folhosa e defina datas diferentes de semeadura. O intervalo real deve considerar cultivar, germinação, ritmo de crescimento e consumo. Observe o resultado antes de repetir.'],table=[['Lote','Meu planejamento'],['A','Data de início: __________  Cultivar: __________'],['B','Próxima entrada: _________  Condição climática: _________'],['C','Espaço disponível em: _________'],['Revisão','Estou colhendo mais do que consigo usar? __________']],tip='Produção contínua é um objetivo de planejamento, não garantia de colheita o ano inteiro em qualquer região.',refs=['U7']),
P('Aprenda a multiplicar sem pressa.','MÓDULO 8 · MUDAS E PROPAGAÇÃO',[
'Algumas ervas podem ser multiplicadas por divisão de touceiras ou por estacas; outras são mais práticas por sementes. Use uma planta-mãe saudável, material identificado e ferramentas limpas. O método depende da espécie.',
'Na divisão, separe uma porção com raízes e brotos viáveis e replante com cuidado. Em estacas de espécies apropriadas, retire um segmento saudável e acompanhe o enraizamento no meio indicado. Não há um tamanho ou prazo único válido para qualquer erva.'],steps=['Escolha um método adequado à espécie.','Prepare recipiente e identificação antes do corte.','Evite retirar material demais da planta-mãe.','Acompanhe umidade e adaptação sem encharcar.'],tip='Rebrotar um pedaço de hortaliça em água é uma experiência; não prova que ele produzirá indefinidamente sem nutrição e manejo.',refs=['M1']),
P('Cultivo sem solo: entenda o sistema.','MÓDULO 9 · INTRODUÇÃO À HIDROPONIA',[
'Na hidroponia, as raízes recebem água e nutrientes por uma solução. A planta ainda precisa de luz, oxigênio e suporte. Água pura em um pote não substitui esses requisitos durante todo o ciclo.',
'Um sistema doméstico de raízes em solução precisa de recipiente apropriado, suporte para as plantas e controle das condições da água. Começar com folhosas pode ser mais simples que iniciar com plantas grandes de frutos.'],steps=['Escolha um sistema específico e siga seu manual.','Use recipiente adequado, opaco e protegido de acesso indevido.','Planeje a oxigenação conforme o sistema.','Use nutrientes formulados para hidroponia, conforme fabricante e cultura.'],tip='Não coloque esterco, chá de composto ou resíduos de cozinha no reservatório. Este volume apresenta conceitos; a instalação exige instruções próprias do sistema.',refs=['M5'],diagram='hydro'),
P('O que monitorar no cultivo sem solo.','MÓDULO 9 · CONTROLE',[
'O pH indica a condição ácido-base da solução; a condutividade elétrica (CE) ajuda a acompanhar a concentração de sais. Ambos devem ser interpretados com a espécie, a fase da planta, a água de origem e a solução utilizada.',
'Não existe uma dose única de nutrientes para toda água e todo sistema. Use medidores apropriados, faça a calibração indicada e siga faixas definidas para o cultivo. Evite correções com produtos domésticos ou misturas sem orientação.'],table=[['Registro','O que acompanhar'],['Água','Origem, reposição e aspecto.'],['Medições','pH, CE, data e calibração do equipamento.'],['Raízes','Cor, integridade e sinais de alteração.'],['Sistema','Aeração, circulação, temperatura e luz no reservatório.']],tip='Falhas em bombas e oxigenação podem exigir resposta rápida. Só adote o sistema se puder acompanhar sua operação.',refs=['M5']),
P('Planeje continuidade com o seu clima.','MÓDULO 9 · CALENDÁRIO',[
'No Brasil, altitude, latitude e regime de chuvas mudam a época favorável de cada cultivo. Um calendário nacional com meses fixos pode orientar mal quem está em outra região. Use a indicação local da cultivar como ponto de partida.',
'Agrupe suas decisões em períodos mais frescos, mais quentes, mais chuvosos e mais secos. O calendário extra da coleção oferece uma matriz para preencher com as informações locais e os resultados que você observar.'],steps=['Selecione espécies compatíveis com o próximo período.','Confira a data provável de ocupação de cada recipiente.','Planeje reposição de mudas e armazenamento de sementes.','Reavalie após mudanças de estação ou eventos extremos.'],tip='Calendários de instituições estrangeiras explicam princípios, mas seus meses e estações não devem ser copiados para o Brasil.',refs=['E1','U9']),
P('Quanto sua horta pede de você?','MÓDULO 9 · PLANEJAMENTO PRÁTICO',[
'Registre o investimento e o tempo de cuidado. Economia de mercado não é garantida: vasos, substrato, mudas, água e perdas fazem parte da conta. O registro ajuda a escolher onde vale ampliar e o que pode ser simplificado.',
'Distingua compras duráveis de gastos que se repetem. Um recipiente pode servir a vários ciclos; substrato e nutrição exigem acompanhamento. Compare colheitas aproveitadas, não apenas volume produzido.'],table=[['Item','Valor / quantidade / observação'],['Estrutura e recipientes','________________________________'],['Substrato, sementes e mudas','________________________________'],['Insumos e reposições','________________________________'],['Colheita que usei','________________________________'],['Tempo de cuidado','________________________________']],tip='Inclua também o que você aprendeu. Uma experiência pequena pode orientar melhor a próxima compra que uma estrutura grande montada de uma vez.'),
P('Meu próximo experimento.','FOLHA PARA IMPRIMIR',[
'Escolha uma única mudança e acompanhe por um ciclo compatível com a espécie. Tente manter as outras condições parecidas. O objetivo é aprender sobre o seu espaço, sem apresentar uma observação doméstica como prova universal.'],fields=['O que quero aprender:','O que vou mudar:','O que vou manter parecido:','Espécie, cultivar e datas:','Como vou registrar o resultado:','O que aconteceu e o que aprendi:'],tip='Exemplo: comparar dois locais para a mesma espécie. Registre a luz e a secagem de cada vaso para interpretar o resultado.')
]))

BOOKS.append(dict(slug='04-calendario-de-plantio',title='Calendário de Plantio',subtitle='Um planejamento anual adaptado ao seu clima.',tag='EXTRA 1 · PLANEJAMENTO',cover='horta-vertical.webp',pages=[
P('O calendário começa na sua região.','ANTES DE ESCOLHER O MÊS',[
'Este calendário é adaptável. Ele não atribui os mesmos meses de semeadura a todo o Brasil, porque a janela favorável muda com região, altitude, cultivar e objetivo de colheita.',
'Consulte o envelope de sementes, o fornecedor de mudas ou a assistência técnica local. Depois preencha as páginas anuais. Os espaços em branco servem para personalizar o planejamento, não indicam falta de orientação.'],steps=['Anote município e condição do espaço.','Liste as cultivares que pretende usar.','Confirme a janela local de semeadura ou transplante.','Marque plantio, acompanhamento e previsão de colheita.'],fields=['Município / estado / condição de altitude:','Períodos locais de chuva, calor e frio:'],tip='Previsão de colheita é uma faixa. A data observada deve substituir a estimativa ao longo do cultivo.',refs=['E1','U9']),
P('Escolha conforme a condição.','MATRIZ DE DECISÃO',[
'Use estas tendências para fazer perguntas ao fornecedor; não substituem a recomendação da cultivar. Dentro de uma mesma espécie existem materiais mais tolerantes ao calor, ao florescimento precoce e a certas condições locais.'],table=[['Condição local','Como planejar'],['Período mais fresco','Considere folhosas e raízes com adaptação local; avalie risco de geada.'],['Período mais quente','Verifique cultivares adequadas; manjericão e tomate exigem condições compatíveis.'],['Chuva frequente','Priorize drenagem, ventilação e acompanhamento de folhas.'],['Período seco / vento','Confira a secagem dos recipientes e a disponibilidade de água.'],['Luz insuficiente','Reveja local e espécie antes de insistir no calendário.']],tip='Plantar no mês sugerido não compensa falta de luz ou recipiente inadequado.',refs=['U9','M6']),
P('Seu ano: janeiro a junho.','CALENDÁRIO ANUAL · 1º SEMESTRE',[
'Em cada mês, registre a espécie e a cultivar cuja janela local foi confirmada. Use S para semear, T para transplantar, A para acompanhar e C para colheita prevista. Não trate a letra C como garantia.'],table=[['Mês','Espécie / cultivar','S / T / A / C'],['Janeiro','___________________','____________'],['Fevereiro','___________________','____________'],['Março','___________________','____________'],['Abril','___________________','____________'],['Maio','___________________','____________'],['Junho','___________________','____________']],fields=['Fonte da recomendação local:','Condições que podem mudar o plano:'],tip='Repita o formulário para mais de uma espécie. Um único mês pode ter atividades diferentes em cada vaso.'),
P('Seu ano: julho a dezembro.','CALENDÁRIO ANUAL · 2º SEMESTRE',[
'Na mudança de estação, reveja o mapa de luz: sombras de prédios e da própria estrutura podem mudar. Atualize a escolha antes de repetir automaticamente o plantio do semestre anterior.'],table=[['Mês','Espécie / cultivar','S / T / A / C'],['Julho','___________________','____________'],['Agosto','___________________','____________'],['Setembro','___________________','____________'],['Outubro','___________________','____________'],['Novembro','___________________','____________'],['Dezembro','___________________','____________']],fields=['Fonte da recomendação local:','O que vou repetir / o que vou mudar:'],tip='Registre a colheita real. Ela ajuda a planejar melhor o próximo ano do que uma estimativa genérica.'),
P('Organize três lotes pequenos.','FICHA DE SUCESSÃO',[
'Depois de escolher a espécie e a época, distribua lotes para evitar colher tudo de uma vez. Defina o intervalo a partir do ciclo indicado e da sua experiência. Ajuste o tamanho dos lotes ao consumo da casa.'],table=[['Lote','Plantio real','Colheita prevista / real'],['A','____________','______________________'],['B','____________','______________________'],['C','____________','______________________']],fields=['Espécie e cultivar:','Intervalo escolhido entre lotes e motivo:','Quantas plantas foram suficientes para meu consumo:','Ajuste para o próximo ciclo:'],tip='Se o clima deixar de ser adequado, mude o planejamento em vez de manter uma sucessão que não faz mais sentido.',refs=['U7'])
]))

BOOKS.append(dict(slug='05-checklist-da-horta',title='Checklist da Horta',subtitle='Observe, decida e registre cada cuidado.',tag='EXTRA 2 · ROTINA',cover='cebolinha-alecrim.webp',pages=[
P('Checar não é intervir sempre.','COMO USAR O CHECKLIST',[
'Uma checagem serve para decidir se uma ação é necessária. Marcar um dia na tabela não significa colocar água ou fertilizante. Use um registro por vaso quando as plantas tiverem necessidades diferentes.',
'Imprima novas cópias quando precisar. Nos campos de observação, escreva sinais concretos: substrato úmido, broto novo, folha caída, data de mudança de lugar. Evite conclusões sem evidência, como “falta adubo”, antes de investigar.'],steps=['Observe luz, água e aparência geral.','Anote o que mudou desde a última checagem.','Faça apenas a ação necessária.','Registre a resposta na próxima observação.'],tip='Uma foto feita do mesmo ângulo pode ajudar a comparar o desenvolvimento.'),
P('Antes de começar o cultivo.','CHECKLIST DE MONTAGEM',steps=['Identifiquei a espécie e a cultivar.','Confirmei a época indicada para minha região.','Observei o período de sol direto.','Escolhi recipiente adequado ao porte adulto.','Conferi furos livres e local de escoamento.','Usei substrato de procedência conhecida.','Li se o substrato já contém adubo.','Separei regador e identificação do plantio.','Verifiquei estabilidade e acesso ao vaso.'],fields=['Pendências antes de plantar:','Data e identificação do vaso:'],tip='Não use recipientes que armazenaram substâncias perigosas.',refs=['U1']),
P('Uma semana de observações.','REGISTRO DIÁRIO',[
'Anote a condição e a decisão. Escrever “não reguei: substrato ainda úmido” é um registro útil. Em dias de calor ou vento, você pode precisar observar mais de uma vez.'],table=[['Dia','O que observei','O que fiz'],['Segunda','________________','________________'],['Terça','________________','________________'],['Quarta','________________','________________'],['Quinta','________________','________________'],['Sexta','________________','________________'],['Sábado','________________','________________'],['Domingo','________________','________________']],fields=['Espécie / vaso / semana:','Principal mudança observada:'],tip='Use o toque no substrato e o peso do vaso como pistas, junto com a necessidade da espécie.',refs=['U2']),
P('Revisão da semana.','CHECKLIST DE ACOMPANHAMENTO',steps=['Observei o verso das folhas e as brotações.','Conferi se a drenagem continua livre.','Retirei água parada de cachepôs e suportes.','Chequei tutores e amarrações.','Retirei restos caídos quando necessário.','Comparei fotos e anotações.','Revisei a necessidade de adubação pelo rótulo e pelo histórico.','Anotei a próxima semeadura ou reposição.'],fields=['Uma coisa que funcionou:','Uma dúvida que preciso investigar:','Próxima ação e data de revisão:'],tip='Sem necessidade de intervenção, mantenha a observação. Evite transformar uma rotina simples em excesso de manejo.'),
P('Ficha de intervenção e resposta.','HISTÓRICO DO VASO',[
'Preencha quando mudar local, transplantar, adubar, remover pragas ou corrigir escoamento. O objetivo é saber o que foi feito e não repetir aplicações sem controle.'],fields=['Data / planta / identificação do vaso:','Sinal observado antes da ação:','Verificação realizada:','Ação / produto / dose indicada e quantidade utilizada:','Resposta observada e data:','Próxima decisão:'],tip='Se houver produto aplicado, guarde a embalagem e siga todas as instruções. Não invente intervalos de segurança.')
]))

BOOKS.append(dict(slug='06-adubos-caseiros',title='Adubos Caseiros',subtitle='Compostagem e matéria orgânica com uso consciente.',tag='EXTRA 3 · CONSULTA',cover='manjericao-vaso.webp',pages=[
P('Aproveitar resíduos exige processo.','COMECE PELO PRINCÍPIO',[
'Este material ensina a organizar a compostagem e a avaliar o uso de matéria orgânica. Ele não promete que uma mistura de cascas substitua toda a nutrição da horta. Resíduos precisam passar por decomposição adequada antes de se tornarem um insumo mais estável.',
'A origem importa. Materiais contaminados, plantas doentes e resíduos tratados com substâncias desconhecidas não devem entrar automaticamente na composteira. Escolha ingredientes conhecidos e mantenha o processo acompanhado.'],steps=['Separe materiais antes de misturar.','Equilibre resíduos úmidos com materiais secos.','Mantenha aeração e acompanhe a umidade.','Use o composto somente quando estiver estabilizado.'],tip='Composto melhora o sistema de cultivo, mas não possui uma concentração fixa de nutrientes para qualquer situação.',refs=['E3']),
P('O que entra na composteira simples.','TRIAGEM DOS MATERIAIS',[
'As orientações abaixo se destinam a uma composteira doméstica de iniciante, sem validação de tratamento térmico. Sistemas profissionais e outros métodos podem ter regras diferentes.'],table=[['Comece com','Deixe fora neste sistema'],['Restos crus de frutas e hortaliças','Carne, peixe, ossos e laticínios'],['Folhas secas limpas','Fezes de cães, gatos e outros animais'],['Pequenos resíduos vegetais de origem conhecida','Plantas muito doentes e resíduos químicos'],['Borra em pequenas porções, bem misturada','Óleo, alimentos muito gordurosos e lixo misturado']],tip='Tenha material seco disponível antes de começar a acumular resíduos úmidos.',refs=['U5']),
P('Monte e acompanhe o processo.','PASSO A PASSO',[
'Use recipiente ou estrutura apropriada ao método, com ventilação e proteção contra animais e chuva excessiva. Misture os materiais para evitar bolsões muito molhados. Não compacte a massa.',
'Uma mistura apenas com sobras úmidas tende a perder aeração. Acrescente folhas secas ou outro material seco limpo, revolva conforme o método e observe. Uma composteira muito seca também pode ter decomposição lenta.'],steps=['Pique os resíduos maiores.','Misture úmidos e secos, sem fazer uma massa encharcada.','Cubra as novas adições.','Acompanhe odor, umidade e aspecto.','Separe material em maturação de novas sobras quando o sistema permitir.'],tip='Não há prazo universal para ficar pronto. Ingredientes, temperatura, volume e manejo alteram o tempo.',refs=['U5','E3']),
P('Borra, banana e casca de ovo.','LIMITES DAS RECEITAS POPULARES',[
'Borra de café: prefira pequenas quantidades misturadas na compostagem. Ela não deve formar uma camada espessa sobre o substrato. Seu uso não dispensa conhecer a necessidade nutricional da planta.',
'Casca de banana: encaminhe como resíduo orgânico. Água de banana não fornece uma formulação medida de nutrientes nem é solução comprovada para qualquer problema.',
'Casca de ovo: sua presença não significa disponibilidade imediata de cálcio. Não use como correção rápida de sintomas. O manejo depende da causa e das condições do solo ou substrato.'],tip='Não pulverize líquidos de decomposição ou receitas fermentadas em folhas destinadas ao consumo.',refs=['O1','U4']),
P('Pronto para usar? Confira primeiro.','MATURIDADE E APLICAÇÃO',[
'Procure um composto estabilizado, escuro, sem aspecto de resíduos frescos dominantes e com cheiro de terra. Odor desagradável persistente, aquecimento após revolvimento e materiais ainda reconhecíveis em grande quantidade pedem mais avaliação e tempo.',
'A quantidade a usar depende da composição do material, do substrato que já existe e da cultura. Sem conhecer isso, não estabeleça uma colher por vaso como regra. Para o primeiro uso, prefira produto identificado ou orientação técnica sobre sua mistura.'],steps=['Verifique origem e maturidade.','Evite contato de resíduos não estabilizados com raízes e alimentos.','Registre quantidade, data e resposta.','Mantenha sementes e mudas em condições apropriadas de germinação.'],tip='O líquido que escorre de uma composteira não deve ser tratado automaticamente como fertilizante seguro.',refs=['U5','U4']),
P('Ficha do meu lote de composto.','FOLHA PARA IMPRIMIR',fields=['Data de início e tipo de sistema:','Materiais colocados e origem:','O que acrescentei para equilibrar umidade e aeração:','Odor, aspecto e mudanças observadas:','Data da avaliação de maturidade:','Destino, quantidade aplicada e resposta das plantas:'],tip='Um registro simples permite reconhecer erros e repetir um processo que funcionou nas suas condições.')
]))

BOOKS.append(dict(slug='07-plantas-para-comecar',title='Plantas para Começar',subtitle='Fichas de consulta para escolher sua primeira horta.',tag='EXTRA 4 · ESPÉCIES',cover='cebolinha-alecrim.webp',pages=[
P('Escolha pelo espaço e pelo uso.','ANTES DAS FICHAS',[
'Estas fichas resumem decisões úteis para começar. Elas não substituem a informação da cultivar: porte, espaçamento e janela de plantio variam. Leve a lista ao fornecedor e confirme se a planta combina com sua região.',
'Comece com uma ou duas espécies que você já usa. Registre a resposta antes de aumentar a quantidade. Os nomes científicos ajudam a evitar confusões entre plantas com nomes populares parecidos.'],table=[['Se você procura...','Considere investigar...'],['Tempero para colher aos poucos','Manjericão ou cebolinha'],['Folhas para acompanhar crescimento','Alface ou rúcula'],['Experiência de semeadura direta','Coentro ou rabanete'],['Uma etapa com mais manejo','Tomate de cultivar apropriada para vaso']],tip='Não identifique plantas comestíveis apenas por fotos deste guia. Compre material corretamente identificado.',refs=['E2','M1']),
P('Manjericão.','OCIMUM BASILICUM',[
'Perfil: erva aromática que se desenvolve bem em condições quentes e com boa luz. Pode ser iniciada por sementes ou mudas. Para o primeiro vaso, a muda identificada permite começar observando os cuidados.',
'Cuidados: mantenha rega compatível com o substrato e evite encharcamento. Acompanhe folhas e brotações. Colha ramos acima de um par de folhas, preservando vegetação suficiente para continuar crescendo.',
'Atenção: floração muda o direcionamento do crescimento. Se o objetivo for folhas, a retirada de hastes florais pode ajudar. Não exponha de repente uma muda de ambiente protegido a condições extremas.'],image='manjericao-vaso.webp',tip='Pergunte ao fornecedor sobre porte e adaptação da cultivar escolhida.',refs=['U8']),
P('Cebolinha e salsa.','ALLIUM FISTULOSUM / PETROSELINUM CRISPUM',[
'Cebolinha: confirme a espécie na compra, pois o nome popular pode ser usado para plantas diferentes. Pode ser iniciada por sementes ou divisão de touceira saudável. Colha preservando a base e acompanhe a retomada das folhas.',
'Salsa: normalmente iniciada por sementes ou mudas. Sua germinação pode exigir paciência; use o intervalo informado pelo fornecedor e não descarte o recipiente antes de avaliar o lote e as condições.',
'Para ambas: planeje espaço para o desenvolvimento, luz adequada e irrigação sem encharcar. Colher moderadamente mantém folhas para a planta continuar seu crescimento.'],tip='Identifique cada vaso com data e nome. Isso evita confundir ritmos de germinação e necessidade de cuidados.',refs=['M1','E1']),
P('Coentro e rabanete.','CORIANDRUM SATIVUM / RAPHANUS SATIVUS',[
'Coentro: é uma opção de semeadura direta. O calor pode acelerar a emissão de flores, conforme cultivar e condições. Semeaduras em pequenos lotes ajudam a acompanhar o uso das folhas sem depender de uma única leva.',
'Rabanete: semeie no local definitivo e respeite a profundidade e o espaçamento indicados. O desbaste é importante para a formação das raízes. Verifique o ponto de colheita pelo tamanho esperado da cultivar.',
'Para ambos: evite semear densamente só porque as sementes cabem no vaso. Espaço disponível e luz devem comportar as plantas quando crescerem.'],tip='Não use uma data de colheita igual para todo lote. Compare o desenvolvimento e as informações do envelope.',refs=['M1','E1']),
P('Alface e rúcula.','LACTUCA SATIVA / ERUCA VESICARIA',[
'Alface: escolha cultivar recomendada para a estação. Existem tipos com diferenças de porte e tolerância ao calor. Pode ser iniciada por muda ou semente. Em tipos de folhas adequados à colheita parcial, preserve o centro de crescimento.',
'Rúcula: normalmente pode ser iniciada por semeadura direta. Respeite a densidade e acompanhe umidade e ponto de corte. O sabor e a textura mudam com idade e condições de cultivo.',
'Para ambas: confirme adaptação ao clima local. Em condições desfavoráveis, trocar a cultivar ou a época pode ser mais útil que insistir com mais adubo.'],tip='Cultivar para o próprio consumo inclui higienizar corretamente o que será levado à cozinha.',refs=['U9','F1']),
P('Tomate: escolha a cultivar primeiro.','SOLANUM LYCOPERSICUM',[
'Perfil: planta que exige luz, volume de recipiente e nutrição compatíveis com seu crescimento. Uma cultivar de frutos pequenos pode formar uma planta grande. Procure identificação de porte e recomendação para vasos.',
'Cuidados: instale apoio antes que os ramos fiquem pesados. Mantenha amarrações sem estrangular o caule e observe a umidade. A condução e a necessidade de retirar brotos variam com o tipo de crescimento.',
'Seu primeiro passo: leve ao fornecedor as medidas do vaso e o mapa de luz. Se não houver espaço adequado, comece com um tempero enquanto planeja um local melhor.'],image='tomates-cereja.webp',tip='O objetivo não é cultivar todas as espécies, mas escolher as que combinam com as suas condições.',refs=['M2'])
]))
