from pathlib import Path
from html import escape
R=Path(__file__).resolve().parents[1]
old=(R/'backups/antes-otimizacao/index.html').read_text(encoding='utf-8')
head=old.split('<body>')[0].replace('https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?auto=format&fit=crop&w=1200&q=80','imagens/horta-infinita-guia-mockup.webp')
plans=[
('essencial','Essencial','7,90','Seu primeiro vaso, com orientação.','1 PDF · Módulos 1 a 5',['Guia Essencial: do local à primeira colheita','Escolha de vasos, luz e substrato','Sementes, mudas e rotina de rega','Temperos e hortaliças para começar'],'https://pay.lowify.com.br/checkout?product_id=kjttls'),
('plus','Plus','12,90','Para cuidar melhor e corrigir problemas.','2 PDFs · Módulos 1 a 7',['Tudo do Essencial','Guia Plus: adubação e problemas comuns','Compostagem e uso responsável de adubos','Inspeção de pragas e registro de cuidados'],'https://pay.lowify.com.br/go.php?offer=laixs9z'),
('completo','Completo','17,90','A coleção para começar e continuar.','7 PDFs · Módulos 1 a 9 + 4 extras',['Tudo do Plus','Guia Avançado: espaço, sucessão e hidroponia introdutória','Calendário de Plantio adaptável ao clima','Checklist da Horta','Adubos Caseiros: compostagem e uso consciente','Plantas para Começar: fichas de consulta'],'https://pay.lowify.com.br/go.php?offer=82j9nx7')]
cards=[]
for tier,name,price,summary,count,features,url in plans:
 cards.append(f'''<article class="pricing-card offer-card {'offer-recommended' if tier=='completo' else ''}" id="plano-{tier}"><div class="offer-label">{'COLEÇÃO COMPLETA' if tier=='completo' else 'COMECE AQUI' if tier=='essencial' else 'MAIS CUIDADOS'}</div><h3 class="plan-name">Horta Infinita {name}</h3><p class="plan-summary">{summary}</p><p class="offer-count">{count}</p><div class="offer-price"><span>R$</span> {price}</div><p class="payment-terms">Pagamento único · Arquivos em PDF</p><ul class="offer-features">{''.join('<li>'+escape(x)+'</li>' for x in features)}</ul><a class="btn btn-primary btn-block checkout-link" href="{escape(url)}" data-tier="{tier}">QUERO O {name.upper()} POR R$ {price}</a><p class="offer-checkout-note">Pagamento pela Lowify · Garantia de 7 dias</p></article>''')
faq=[('O que vou receber?','Você recebe os PDFs do plano escolhido: 1 no Essencial, 2 no Plus ou 7 no Completo. São materiais de leitura com imagens, orientações e páginas de planejamento. Não inclui videoaulas, plantas ou itens físicos.'),('Preciso ter experiência ou quintal?','Não precisa ter experiência. O guia começa pela escolha do espaço e pode ser aplicado a vasos, varandas e quintais. O cultivo depende de luz adequada, recipiente compatível e cuidados com cada espécie.'),('Qual é a diferença entre os planos?','O Essencial cobre os módulos 1 a 5. O Plus acrescenta adubação e problemas comuns, nos módulos 6 e 7. O Completo inclui tudo isso, os módulos 8 e 9 e quatro PDFs extras de consulta e planejamento.'),('Como recebo o acesso?','Após a confirmação do pagamento, siga as instruções de acesso apresentadas pela Lowify e no e-mail da compra. Utilize um e-mail correto no checkout e confira também a pasta de spam.'),('Posso ler no celular e imprimir?','Sim. Os arquivos podem ser abertos no celular, tablet ou computador e impressos para uso pessoal. Você pode guardar uma cópia para consultar depois.'),('É uma assinatura?','Não. O pagamento é único para o pacote escolhido. Não há mensalidade do Horta Infinita nesta oferta.'),('Existe garantia?','Você tem 7 dias para conhecer o material e solicitar reembolso pelo atendimento da compra ou pela plataforma de pagamento. Guarde o comprovante e os dados do pedido.')]
faq_html=''.join(f'<div class="faq-item"><button type="button" class="faq-trigger" aria-expanded="false" aria-controls="faq-{i}" id="faq-button-{i}"><span>{q}</span><span aria-hidden="true">+</span></button><div class="faq-content" id="faq-{i}" role="region" aria-labelledby="faq-button-{i}"><p>{a}</p></div></div>' for i,(q,a) in enumerate(faq,1))
body='''<body>
<a href="#conteudo-principal" class="skip-link">Pular para o conteúdo principal</a><div class="mobile-app-shell">
<header class="top-announcement"><div class="announcement-content"><span class="announcement-text">GUIAS EM PDF · A PARTIR DE R$ 7,90 · PAGAMENTO ÚNICO</span></div></header>
<main id="conteudo-principal">
<section class="section hero-section" id="inicio"><div class="hero-content"><div class="hero-brand-wrapper"><div class="hero-brand-badge"><span aria-hidden="true">🌿</span><span class="hero-brand-title">Horta Infinita</span><span aria-hidden="true">🌿</span></div></div>
<h1 class="hero-title">Seu primeiro vaso pode ser <span class="highlight-text">o começo da sua horta.</span></h1><p class="hero-subtitle">Aprenda a escolher o lugar, plantar e cuidar dos seus temperos com guias em PDF, mesmo começando do zero.</p>
<div class="vsl-wrapper"><div class="vsl-container"><video id="vslPlayer" class="horta-video" controls playsinline preload="none" poster="imagens/video-poster.webp" width="1280" height="720" aria-label="Apresentação Horta Infinita"><source src="video/horta-infinita-gancho.mp4" type="video/mp4"><p>Seu navegador não reproduz este vídeo. Leia a apresentação abaixo.</p></video></div></div><p class="video-helper">Dê o play e imagine sua primeira colheita.</p>
<p id="videoFallback" hidden>Não foi possível carregar o vídeo. Leia a apresentação abaixo.</p><details class="video-transcript" id="videoTranscript"><summary>Ler a apresentação do vídeo</summary><p>Já imaginou colher o tempero do almoço a poucos passos da sua cozinha? Você pode começar com um vaso, a planta certa e um lugar com luz adequada. O Horta Infinita reúne guias em PDF para aprender sobre plantio, rega e cuidados. Comece pelo Essencial e avance no seu ritmo. Escolha seu acesso a partir de sete reais e noventa centavos.</p></details>
<div class="hero-cta-box"><a class="btn btn-primary btn-large btn-block" href="#ofertas">QUERO ESCOLHER MEU GUIA <span aria-hidden="true">↓</span></a><div class="hero-price-sub"><span class="price-call">Planos a partir de</span><span class="price-value">R$ 7,90</span><span class="price-mode">· Pagamento único</span></div></div><div class="hero-indicators"><div class="indicator-item">🌱 Para iniciantes</div><div class="indicator-item">📱 PDFs para consultar</div><div class="indicator-item">🛡️ Garantia de 7 dias</div></div></div></section>
<section class="section identification-section" id="identificacao"><div class="section-header text-center"><span class="section-badge">Um cuidado de cada vez</span><h2 class="section-title">Não sabe por onde começar?</h2><p class="section-desc">Transforme as dúvidas do dia a dia em decisões mais simples.</p></div><div class="grid-cards-vertical"><div class="card-pain"><span class="pain-icon">☀️</span><p class="pain-text"><strong>Onde colocar o vaso?</strong><br>Observe a luz do seu espaço e escolha espécies compatíveis.</p></div><div class="card-pain"><span class="pain-icon">💧</span><p class="pain-text"><strong>É hora de regar?</strong><br>Aprenda a observar o substrato, sem uma regra igual para todas as plantas.</p></div><div class="card-pain"><span class="pain-icon">🌱</span><p class="pain-text"><strong>O que plantar primeiro?</strong><br>Comece com poucas espécies e acompanhe a evolução de cada uma.</p></div></div></section>
<section class="section mockup-section" id="produto"><div class="section-header text-center"><span class="section-badge">Sua biblioteca de cultivo</span><h2 class="section-title">Orientação para ter à mão.</h2><p class="section-desc">Leia, consulte e volte ao assunto quando surgir uma dúvida.</p></div><img src="imagens/horta-infinita-guia-mockup.webp" width="1536" height="1024" loading="lazy" decoding="async" class="product-visual" alt="Representação dos guias digitais Horta Infinita em tablet e celular"><p class="image-caption">Representação visual do produto digital. Dispositivos não inclusos.</p><div class="mockup-perks"><div class="perk-pill">PDFs com imagens e instruções</div><div class="perk-pill">Páginas de planejamento para imprimir</div><div class="perk-pill">Fontes técnicas indicadas nos materiais</div></div></section>
<section class="section sample-section" id="por-dentro"><div class="section-header text-center"><span class="section-badge">Veja antes de escolher</span><h2 class="section-title">Páginas reais do seu guia.</h2><p class="section-desc">Amostras do PDF Essencial. Toque para ampliar.</p></div><div class="sample-grid"><a href="imagens/amostra-essencial-1.webp" target="_blank" rel="noopener"><img src="imagens/amostra-essencial-1.webp" alt="Página real do guia: observação da luz no espaço" width="1000" height="1400" loading="lazy" decoding="async"></a><a href="imagens/amostra-essencial-2.webp" target="_blank" rel="noopener"><img src="imagens/amostra-essencial-2.webp" alt="Página real do guia: cuidados com a rega" width="1000" height="1400" loading="lazy" decoding="async"></a></div></section>
<section class="section curriculum-section" id="conteudo"><div class="section-header text-center"><span class="section-badge">Uma trilha progressiva</span><h2 class="section-title">Escolha até onde quer ir.</h2></div><details class="curriculum-detail"><summary><strong>Essencial · Módulos 1 a 5</strong><span>Do primeiro vaso aos cuidados básicos</span></summary><p>1. Primeiros passos e escolha do espaço<br>2. Vasos, solo e substrato<br>3. Sementes, mudas e plantio<br>4. Rega e cuidados diários<br>5. Temperos, hortaliças e colheita</p></details><details class="curriculum-detail"><summary><strong>Plus · Acrescenta os módulos 6 e 7</strong><span>Adubação e problemas comuns</span></summary><p>6. Nutrição, adubação e compostagem<br>7. Inspeção, manejo de pragas e recuperação</p></details><details class="curriculum-detail"><summary><strong>Completo · Acrescenta os módulos 8 e 9</strong><span>Mais espaço, continuidade e técnicas</span></summary><p>8. Hortas verticais, consórcio, sucessão e mudas<br>9. Introdução ao cultivo sem solo e planejamento da produção<br>Mais quatro PDFs extras de consulta e organização.</p></details></section>
<section class="section pricing-section" id="ofertas"><div class="section-header text-center"><span class="section-badge">O conteúdo certo para sua etapa</span><h2 class="section-title">Três opções. Você escolhe.</h2><p class="section-desc">Todos os planos são digitais e têm pagamento único. Compare os arquivos de cada opção.</p></div><div class="pricing-vertical-layout">__CARDS__</div><p class="offer-explanation">Do Essencial para o Plus: + R$ 5,00. Do Plus para o Completo: + R$ 5,00. Os valores são os preços totais de cada pacote, não parcelas.</p></section>
<section class="section bonuses-section" id="bonus"><div class="section-header text-center"><span class="section-badge">Exclusivos do plano Completo</span><h2 class="section-title">Quatro extras para usar na prática.</h2></div><img src="imagens/horta-infinita-bonus-mockup.webp" width="1536" height="1024" loading="lazy" decoding="async" class="product-visual" alt="Representação dos quatro PDFs extras: Calendário de Plantio, Checklist da Horta, Adubos Caseiros e Plantas para Começar"><p class="image-caption">Capas ilustrativas. Os quatro arquivos estão inclusos no Completo.</p><div class="bonus-mini-list"><p><strong>Calendário de Plantio:</strong> organize o ano conforme o clima e as cultivares da sua região.</p><p><strong>Checklist da Horta:</strong> registre observações e cuidados sem transformar toda checagem em uma rega.</p><p><strong>Adubos Caseiros:</strong> entenda compostagem, matéria orgânica e os limites das receitas populares.</p><p><strong>Plantas para Começar:</strong> consulte fichas práticas de espécies para sua horta.</p></div></section>
<section class="section guarantee-section"><div class="guarantee-box"><img src="imagens/selo-garantia-7-dias.webp" class="guarantee-seal-img" width="170" height="170" loading="lazy" alt="7 dias de garantia"><h2 class="guarantee-title">Conheça o material com tranquilidade.</h2><p class="guarantee-desc">Você tem 7 dias para conhecer os PDFs. Caso queira solicitar reembolso, utilize o atendimento da compra ou a plataforma de pagamento.</p></div></section>
<section class="section faq-section" id="faq"><div class="section-header text-center"><h2 class="section-title">Antes de começar, tire suas dúvidas.</h2></div><div class="faq-accordion">__FAQ__</div></section>
<section class="section closing-cta-section"><div class="closing-card text-center"><span class="closing-leaf" aria-hidden="true">🌱</span><h2 class="closing-title">Comece pequeno.<br>Aprenda a cada cuidado.</h2><p>Escolha o guia que faz sentido para sua etapa e prepare seu primeiro vaso.</p><a class="btn btn-primary btn-block closing-button" href="#ofertas">ESCOLHER MEU PLANO</a></div></section>
</main><footer class="main-footer text-center"><div class="footer-logo">🌱 <strong>Horta Infinita</strong></div><p class="footer-mission">Guias em PDF sobre cultivo doméstico.</p><ul class="footer-links-inline"><li><a href="#produto">Produto</a></li><li><a href="#ofertas">Planos</a></li><li><a href="#faq">Dúvidas</a></li></ul><div class="footer-bottom"><p>Produto digital de finalidade educacional. Resultados variam conforme clima, espécie, espaço e cuidados. Imagens de ambientação e mockups são ilustrativos.</p><p>© 2026 Horta Infinita. Material para uso pessoal.</p></div></footer></div><script src="script.js"></script></body></html>'''
(R/'index.html').write_text(head+body.replace('__CARDS__',''.join(cards)).replace('__FAQ__',faq_html),encoding='utf-8')
(R/'script.js').write_text('''const CHECKOUT_URLS = Object.freeze({essencial: 'https://pay.lowify.com.br/checkout?product_id=kjttls', plus: 'https://pay.lowify.com.br/go.php?offer=laixs9z', completo: 'https://pay.lowify.com.br/go.php?offer=82j9nx7'});
document.addEventListener('DOMContentLoaded', () => {
 document.querySelectorAll('.checkout-link').forEach(link => { if(CHECKOUT_URLS[link.dataset.tier]) link.href=CHECKOUT_URLS[link.dataset.tier]; });
 document.querySelectorAll('.faq-trigger').forEach(trigger => trigger.addEventListener('click', () => {
  const expanded=trigger.getAttribute('aria-expanded')==='true';
  const content=document.getElementById(trigger.getAttribute('aria-controls'));
  trigger.setAttribute('aria-expanded',String(!expanded));
  trigger.closest('.faq-item').classList.toggle('active',!expanded);
  content.classList.toggle('open',!expanded);
  content.style.maxHeight=expanded?'':`${content.scrollHeight+32}px`;
 }));
 const player=document.getElementById('vslPlayer');
 player.addEventListener('error',()=>{ document.getElementById('videoTranscript').open=true; document.getElementById('videoFallback').hidden=false; });
});
''',encoding='utf-8')
css=(R/'backups/antes-otimizacao/styles.css').read_text(encoding='utf-8')
css+='''
/* Atualização: PDFs, vídeo real e escolha direta entre três planos. */
.horta-video{display:block;width:100%;height:auto;aspect-ratio:16/9;background:#133323;object-fit:contain}
.video-helper,.video-transcript{font-size:.875rem;color:var(--color-text-muted);margin:10px 0 18px;text-align:center}
.video-transcript{text-align:left}.video-transcript summary{cursor:pointer;text-decoration:underline;padding:8px 0}.video-transcript p{padding-top:10px}
.product-visual{width:100%;height:auto;border-radius:16px}.image-caption{font-size:.78rem;line-height:1.5;text-align:center;margin:9px 0 20px;color:var(--color-text-muted)}
.sample-section{background:#fff}.sample-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.sample-grid img{border:1px solid #dcebd7;border-radius:8px;box-shadow:0 5px 20px #13332318}
.curriculum-detail{background:#fff;border:1px solid #dcebd7;border-radius:12px;padding:16px;margin-bottom:12px}.curriculum-detail summary{cursor:pointer;line-height:1.5}.curriculum-detail summary span{display:block;font-size:.875rem;margin-top:4px;color:var(--color-text-muted)}.curriculum-detail p{margin-top:14px;font-size:.95rem;line-height:1.8}
.offer-card{padding:26px 20px;scroll-margin-top:60px}.offer-recommended{border:2px solid #1f4d36;background:#f3f7ef}.offer-label{font-weight:800;letter-spacing:.09em;font-size:.78rem;color:#4d7c52;margin-bottom:12px}.offer-count{font-weight:700;color:#1f4d36;font-size:.9rem;margin:16px 0 6px}.offer-price{font-size:3.15rem;font-weight:800;color:#1f4d36;line-height:1.2}.offer-price span{font-size:1.2rem}.offer-features{list-style:none;margin:22px 0;display:flex;flex-direction:column;gap:12px}.offer-features li{position:relative;padding-left:22px;font-size:1rem;line-height:1.5}.offer-features li:before{content:'✓';position:absolute;left:0;color:#2f8f46;font-weight:bold}.offer-checkout-note{font-size:.8rem;text-align:center;color:#556b5e;margin-top:12px}.offer-explanation{font-size:.875rem;line-height:1.65;margin-top:22px;color:#556b5e}.bonus-mini-list{display:grid;gap:16px;font-size:1rem}.closing-button{margin-top:24px}.hero-indicators{gap:12px}.indicator-item{font-size:.84rem}.faq-content p{font-size:1rem}.faq-trigger{font-size:1rem;min-height:48px}.section-desc,.pain-text{font-size:1rem}#ofertas{scroll-margin-top:52px}.btn{white-space:normal;line-height:1.4;text-align:center;min-height:48px}.top-announcement{position:relative}.main-footer{padding-bottom:40px}
'''
(R/'styles.css').write_text(css,encoding='utf-8')
print('Site atualizado. PDFs, vídeo e amostras serão verificados antes da entrega.')
